{% set name = "libbezier" %}
{% set github_org = "dhermes" %}
{% set github_repo = "bezier" %}
{% set version = "2020.5.19" %}
{% set tar_gz_hash = "ce5a3efc74c733329830b129c2943954213a71c7a5fd500b4cce94ff2347460f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ github_org }}/{{ github_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ tar_gz_hash }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler("fortran") }}        # [linux or osx]
    - make                             # [linux or osx]
    - {{ compiler("m2w64_fortran") }}  # [win]
    - m2w64-toolchain                  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libbezier${SHLIB_EXT}"         # [linux or osx]
    - if not exist %LIBRARY_BIN%\\bezier%SHLIB_EXT% exit 1  # [win]

about:
  home: https://github.com/dhermes/bezier
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Helper for B\xe9zier Curves, Triangles, and Higher Order Objects"

  doc_url: https://bezier.readthedocs.io/en/{{ version }}/
  dev_url: https://github.com/dhermes/bezier

extra:
  recipe-maintainers:
    - dhermes
